version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qntngvs-homeassistant_server_1
  server:
    image: homeassistant/home-assistant:latest@sha256:031d355a2e52e82fc33cd6854753fb19fc5d6a31af6f0f54c277d6f118ad993e
    network_mode: host
    # UI at default port 8123
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /dev:/dev
